---
#######################################
# Master Playbook for generating the user identities
#######################################
- hosts: all
  gather_facts: no
  no_log: True
- import_playbook: environment-setup.yaml   # First setup environment for each organization
- import_playbook: kubernetes-env-setup.yaml # Then deploy Flux for each organization
  when: reset is undefined or reset == 'false'
- import_playbook: "{{ playbook_dir }}/../../hyperledger-fabric/configuration/generate-user-identity.yaml"
  when: network.type == 'fabric' and (reset is undefined or reset == 'false')
